# Generated by Django 4.0.6 on 2022-07-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to="'profiles/"),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to="'profiles/"),
        ),
    ]
