# Generated by Django 4.0.6 on 2022-08-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_business_profile_pic_freelancer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
