# Generated by Django 4.0.6 on 2022-08-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_freelancer_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('principal', 'Principal'), ('cto', 'CTO')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PT', 'Part-Time'), ('FT', 'Full-Time'), ('Contract', 'Contract')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='search_status',
            field=models.CharField(choices=[('active', 'Active'), ('open', 'Open'), ('interested', 'Interested'), ('invisible', 'Invisible')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='stackoverflow',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profile_pic',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='role_level',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.level'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='role_type',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.role'),
        ),
    ]
