# Generated by Django 4.0.6 on 2022-08-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_freelancer_state_freelancer_city_freelancer_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='State',
            new_name='state',
        ),
    ]
