# Generated by Django 4.0.6 on 2022-08-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_state_freelancer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
