# Generated by Django 4.0.6 on 2022-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_freelancer_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='freelancer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
