# Generated by Django 4.0 on 2022-08-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_business_created_at_business_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='role_level',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.Level'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='role_type',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.Role'),
        ),
    ]
